name: Build and deploy simonis.io to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build and publish simonis.io
        uses: ./.github/actions/my-jekyll-action/
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
